version: '3.8'

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=microservice
    volumes:
      - microservice-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@email.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin"
    ports:
      - "6543:80"
    depends_on:
      - postgres

volumes:
  microservice-data: